
package in.gov.incometaxindiaefiling.itrservice.v_1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ITRService", targetNamespace = "http://incometaxindiaefiling.gov.in/itrservice/v_1_0", wsdlLocation = "https://incometaxindiaefiling.gov.in/e-FilingWS/ditws/submitITR.wsdl")
public class ITRService
    extends Service
{

    private final static URL ITRSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITRSERVICE_EXCEPTION;
    private final static QName ITRSERVICE_QNAME = new QName("http://incometaxindiaefiling.gov.in/itrservice/v_1_0", "ITRService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://incometaxindiaefiling.gov.in/e-FilingWS/ditws/submitITR.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITRSERVICE_WSDL_LOCATION = url;
        ITRSERVICE_EXCEPTION = e;
    }

    public ITRService() {
        super(__getWsdlLocation(), ITRSERVICE_QNAME);
    }

    public ITRService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITRSERVICE_QNAME, features);
    }

    public ITRService(URL wsdlLocation) {
        super(wsdlLocation, ITRSERVICE_QNAME);
    }

    public ITRService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITRSERVICE_QNAME, features);
    }

    public ITRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITRService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITRServicePort
     */
    @WebEndpoint(name = "ITRServiceSoapHttpPort")
    public ITRServicePort getITRServiceSoapHttpPort() {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/itrservice/v_1_0", "ITRServiceSoapHttpPort"), ITRServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITRServicePort
     */
    @WebEndpoint(name = "ITRServiceSoapHttpPort")
    public ITRServicePort getITRServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/itrservice/v_1_0", "ITRServiceSoapHttpPort"), ITRServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITRSERVICE_EXCEPTION!= null) {
            throw ITRSERVICE_EXCEPTION;
        }
        return ITRSERVICE_WSDL_LOCATION;
    }

}
