
package in.gov.incometaxindiaefiling.itrvservice.v_1_0;

import javax.xml.ws.WebFault;
import in.gov.incometaxindiaefiling.ws.ds.ex.v_1_0.ITRVInvalidCertificateFaultException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "itrvInvalidCertificateFaultException", targetNamespace = "http://incometaxindiaefiling.gov.in/ws/ds/ex/v_1_0")
public class GetITRVInvalidCertificateFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ITRVInvalidCertificateFaultException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetITRVInvalidCertificateFaultException(String message, ITRVInvalidCertificateFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetITRVInvalidCertificateFaultException(String message, ITRVInvalidCertificateFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: in.gov.incometaxindiaefiling.ws.ds.ex.v_1_0.ITRVInvalidCertificateFaultException
     */
    public ITRVInvalidCertificateFaultException getFaultInfo() {
        return faultInfo;
    }

}
