
package in.gov.incometaxindiaefiling.itrvservice.v_1_0;

import javax.xml.ws.WebFault;
import in.gov.incometaxindiaefiling.ws.ds.ex.v_1_0.ITRVServiceFaultException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "itrvServiceFaultException", targetNamespace = "http://incometaxindiaefiling.gov.in/ws/ds/ex/v_1_0")
public class GetITRVServiceFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ITRVServiceFaultException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetITRVServiceFaultException(String message, ITRVServiceFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetITRVServiceFaultException(String message, ITRVServiceFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: in.gov.incometaxindiaefiling.ws.ds.ex.v_1_0.ITRVServiceFaultException
     */
    public ITRVServiceFaultException getFaultInfo() {
        return faultInfo;
    }

}
