
package in.gov.incometaxindiaefiling.itrvservice.v_1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ITRVService", targetNamespace = "http://incometaxindiaefiling.gov.in/itrvservice/v_1_0", wsdlLocation = "https://incometaxindiaefiling.gov.in/e-FilingWS/ditws/getITRV.wsdl")
public class ITRVService
    extends Service
{

    private final static URL ITRVSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITRVSERVICE_EXCEPTION;
    private final static QName ITRVSERVICE_QNAME = new QName("http://incometaxindiaefiling.gov.in/itrvservice/v_1_0", "ITRVService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://incometaxindiaefiling.gov.in/e-FilingWS/ditws/getITRV.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITRVSERVICE_WSDL_LOCATION = url;
        ITRVSERVICE_EXCEPTION = e;
    }

    public ITRVService() {
        super(__getWsdlLocation(), ITRVSERVICE_QNAME);
    }

    public ITRVService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITRVSERVICE_QNAME, features);
    }

    public ITRVService(URL wsdlLocation) {
        super(wsdlLocation, ITRVSERVICE_QNAME);
    }

    public ITRVService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITRVSERVICE_QNAME, features);
    }

    public ITRVService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ITRVService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITRVServicePortType
     */
    @WebEndpoint(name = "ITRVServicePort")
    public ITRVServicePortType getITRVServicePort() {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/itrvservice/v_1_0", "ITRVServicePort"), ITRVServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITRVServicePortType
     */
    @WebEndpoint(name = "ITRVServicePort")
    public ITRVServicePortType getITRVServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://incometaxindiaefiling.gov.in/itrvservice/v_1_0", "ITRVServicePort"), ITRVServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITRVSERVICE_EXCEPTION!= null) {
            throw ITRVSERVICE_EXCEPTION;
        }
        return ITRVSERVICE_WSDL_LOCATION;
    }

}
